//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmWatson.ConnectorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.confirm.co.uk/schema/am/connector/webservice", ConfigurationName="ConnectorService.ConfirmConnectorSoap")]
    public interface ConfirmConnectorSoap {
        
        // CODEGEN: Generating message contract since the operation ProcessOperations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.confirm.co.uk/schema/am/connector/webservice/ProcessOperations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConfirmWatson.ConnectorService.ProcessOperationsResponse ProcessOperations(ConfirmWatson.ConnectorService.ProcessOperationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.confirm.co.uk/schema/am/connector/webservice/ProcessOperations", ReplyAction="*")]
        System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessOperationsResponse> ProcessOperationsAsync(ConfirmWatson.ConnectorService.ProcessOperationsRequest request);
        
        // CODEGEN: Generating message contract since the operation ProcessFbi is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.confirm.co.uk/schema/am/connector/webservice/ProcessFbi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConfirmWatson.ConnectorService.ProcessFbiResponse ProcessFbi(ConfirmWatson.ConnectorService.ProcessFbiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.confirm.co.uk/schema/am/connector/webservice/ProcessFbi", ReplyAction="*")]
        System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessFbiResponse> ProcessFbiAsync(ConfirmWatson.ConnectorService.ProcessFbiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessOperationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessOperationsRequest", Namespace="http://www.confirm.co.uk/schema/am/connector/webservice", Order=0)]
        public System.Xml.XmlNode ProcessOperationsRequest1;
        
        public ProcessOperationsRequest() {
        }
        
        public ProcessOperationsRequest(System.Xml.XmlNode ProcessOperationsRequest1) {
            this.ProcessOperationsRequest1 = ProcessOperationsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessOperationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.confirm.co.uk/schema/am/connector/webservice", Order=0)]
        public System.Xml.XmlNode ProcessOperationsResult;
        
        public ProcessOperationsResponse() {
        }
        
        public ProcessOperationsResponse(System.Xml.XmlNode ProcessOperationsResult) {
            this.ProcessOperationsResult = ProcessOperationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessFbiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.confirm.co.uk/schema/am/connector/webservice", Order=0)]
        public System.Xml.XmlNode requestDoc;
        
        public ProcessFbiRequest() {
        }
        
        public ProcessFbiRequest(System.Xml.XmlNode requestDoc) {
            this.requestDoc = requestDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessFbiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.confirm.co.uk/schema/am/connector/webservice", Order=0)]
        public System.Xml.XmlNode ProcessFbiResult;
        
        public ProcessFbiResponse() {
        }
        
        public ProcessFbiResponse(System.Xml.XmlNode ProcessFbiResult) {
            this.ProcessFbiResult = ProcessFbiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfirmConnectorSoapChannel : ConfirmWatson.ConnectorService.ConfirmConnectorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfirmConnectorSoapClient : System.ServiceModel.ClientBase<ConfirmWatson.ConnectorService.ConfirmConnectorSoap>, ConfirmWatson.ConnectorService.ConfirmConnectorSoap {
        
        public ConfirmConnectorSoapClient() {
        }
        
        public ConfirmConnectorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfirmConnectorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmConnectorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmConnectorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConfirmWatson.ConnectorService.ProcessOperationsResponse ConfirmWatson.ConnectorService.ConfirmConnectorSoap.ProcessOperations(ConfirmWatson.ConnectorService.ProcessOperationsRequest request) {
            return base.Channel.ProcessOperations(request);
        }
        
        public System.Xml.XmlNode ProcessOperations(System.Xml.XmlNode ProcessOperationsRequest1) {
            ConfirmWatson.ConnectorService.ProcessOperationsRequest inValue = new ConfirmWatson.ConnectorService.ProcessOperationsRequest();
            inValue.ProcessOperationsRequest1 = ProcessOperationsRequest1;
            ConfirmWatson.ConnectorService.ProcessOperationsResponse retVal = ((ConfirmWatson.ConnectorService.ConfirmConnectorSoap)(this)).ProcessOperations(inValue);
            return retVal.ProcessOperationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessOperationsResponse> ConfirmWatson.ConnectorService.ConfirmConnectorSoap.ProcessOperationsAsync(ConfirmWatson.ConnectorService.ProcessOperationsRequest request) {
            return base.Channel.ProcessOperationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessOperationsResponse> ProcessOperationsAsync(System.Xml.XmlNode ProcessOperationsRequest1) {
            ConfirmWatson.ConnectorService.ProcessOperationsRequest inValue = new ConfirmWatson.ConnectorService.ProcessOperationsRequest();
            inValue.ProcessOperationsRequest1 = ProcessOperationsRequest1;
            return ((ConfirmWatson.ConnectorService.ConfirmConnectorSoap)(this)).ProcessOperationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConfirmWatson.ConnectorService.ProcessFbiResponse ConfirmWatson.ConnectorService.ConfirmConnectorSoap.ProcessFbi(ConfirmWatson.ConnectorService.ProcessFbiRequest request) {
            return base.Channel.ProcessFbi(request);
        }
        
        public System.Xml.XmlNode ProcessFbi(System.Xml.XmlNode requestDoc) {
            ConfirmWatson.ConnectorService.ProcessFbiRequest inValue = new ConfirmWatson.ConnectorService.ProcessFbiRequest();
            inValue.requestDoc = requestDoc;
            ConfirmWatson.ConnectorService.ProcessFbiResponse retVal = ((ConfirmWatson.ConnectorService.ConfirmConnectorSoap)(this)).ProcessFbi(inValue);
            return retVal.ProcessFbiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessFbiResponse> ConfirmWatson.ConnectorService.ConfirmConnectorSoap.ProcessFbiAsync(ConfirmWatson.ConnectorService.ProcessFbiRequest request) {
            return base.Channel.ProcessFbiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConfirmWatson.ConnectorService.ProcessFbiResponse> ProcessFbiAsync(System.Xml.XmlNode requestDoc) {
            ConfirmWatson.ConnectorService.ProcessFbiRequest inValue = new ConfirmWatson.ConnectorService.ProcessFbiRequest();
            inValue.requestDoc = requestDoc;
            return ((ConfirmWatson.ConnectorService.ConfirmConnectorSoap)(this)).ProcessFbiAsync(inValue);
        }
    }
}
